print("CHOOSE THE CORRECT OPTION TO WIN THE GAME")
Ques1 = ("Q1. What is the name of the world's largest ocean?")
#here Ques1 is a variable
print(Ques1)
a = ("A) Atlantic Ocean")
b = ("B) Indian Ocean")
c = ("C) Arctic Ocean")
d = ("D) Pacific Ocean")
print(a)
print(b)
print(c)
print(d)
ans = input("Enter your answer: ")
if ans == "d":
  print("Correct answer")
  print("You won 2,000 rupees")
  Ques2 = ("Q2. Who is the current President of India?")
#here Ques2 is a variable
  print(Ques2)
  a = ("a. Obama")
  b = ("b. Droupadi Murmu")
  c = ("c. Joe Biden")
  d = ("d. Vladimir Putin")
  print(a)
  print(b)
  print(c)
  print(d)
  ans = input("Enter your answer: ")
  if ans == "b":
    print("Correct answer")
    print("You won 6,000 rupees")
    #if the answer is correct, then print the next question
    Ques3 = ("Q3. Which country is known as the 'Land of the Rising Sun'?")
    print(Ques3)
    a = ("A) China")
    b = ("B) India")
    c = ("C) Japan")
    d = ("D) Thailand")
    print(a)
    print(b)
    print(c)
    print(d)
    ans = input("Enter your answer: ")
    if ans == "c":
      print("Correct answer")
      print("You won 15,000 rupees")
      #if the answer is correct, then print the next question
      Ques4 = ("Q4. Who is the author of the Harry Potter series?")
      print(Ques4)
      a = ("A) J.K. Rowling")
      b = ("B) Stephen King")
      c = ("C) George R.R. Martin")
      d = ("D) Dan Brown")
      print(a)
      print(b)
      print(c)
      print(d)
      ans = input("Enter your answer: ")
      if ans == "a":
        print("Correct answer")
        print("You won 23,0000 rupees")
        #if the answer is correct, then print the next question
        Ques5 = ("Q5. What is the chemical symbol for gold?")
        print(Ques5)
        a = ("A) Au")
        b = ("B) Ag")
        c = ("C) Fe")
        d = ("D) Cu")
        print(a)
        print(b)
        print(c)
        print(d)
        ans = input("Enter your answer: ")
        if ans == "a":
          print("Correct answer")
          print("You won 35,0000 rupees")
          #if the answer is correct, then print the next question
          Ques6 = ("Q6. Which planet in our solar system is known as the 'Red Planet' ?")

          a = ("A) Mars")
          b = ("B) Venus")
          c = ("C) Jupiter")
          d = ("D) Saturn")
          print(a)
          print(b)
          print(c)
          print(d)
          ans = input("Enter your answer: ")
          if ans == "a":
            print("Correct answer")
            print("You won 50,000 rupees")
            #if the answer is correct, then print the next question
            Ques7 = ("Q7. Who painted the Mona Lisa?")
            print(Ques7)
            a = ("A) Leonardo da Vinci")
            b = ("B) Pablo Picasso")
            c = ("C) Vincent van Gogh")
            d = ("D) Michelangelo")
            print(a)
            print(b)
            print(c)
            print(d)
            ans = input("Enter your answer: ")
            if ans == "a":
              print("Correct answer")
              print("You won 65,000 rupees")
              #if the answer is correct, then print the next question
              Ques8 = ("Q8. Which element is known as 'The King of Chemicals' ? ")
              a = ("A) Oxygen")
              b = ("B) Carbon")
              c = ("C) Nitrogen")
              d = ("D) Sulpher")
              print(a)
              print(b)
              print(c)
              print(d)
              ans = input("Enter your answer: ")
              if ans == "d":
                print("Correct answer")
                print("You won 85,000 rupees")
                #if the answer is correct, then print the next question
                Ques9 = ("Q9. Which is the smallest country in the world in terms of land area ?")
                print(Ques9)
                a = ("A) Vatican City")
                b = ("B) Monaco")
                c = ("C) Nauru")
                d = ("D) San Marino")
                print(a)
                print(b)
                print(c)
                print(d)
                ans = input("Enter your answer: ")
                if ans == "a":
                  print("Correct answer")
                  print("You won 1,00,000 rupees")
                  #if the answer is correct, then print the next question
                  Ques10 = ("Q10. What is the total net volume of the global stock trading ? ")
                  print(Ques10)
                  a = ("A) 103 trillion U.S. dollars")
                  b = ("B) 130 trillion U.S. dollars")
                  c = ("C) 1.3 trillion U.S. dollars")
                  d = ("D) 1.03 trillion U.S. dollars")
                  print(a)
                  print(b)
                  print(c)
                  print(d)
                  ans = input("Enter your answer: ")
                  if ans == "b":
                    print("Correct answer")
                    print("You won 2,00,000 rupees")
                    print("Congratulations! You won the game")
                  else :
                    print("Incorrect answer")
                    print("Thank you for playing")
                else :
                  print("Incorrect answer")
                  print("Thank you for playing")
              else :
                print("Incorrect answer")
                print("Thank you for playing")
            else :
              print("Incorrect answer")
              print("Thank you for playing")
          else :
            print("Incorrect answer")
            print("Thank you for playing")
        else :
          print("Incorrect answer")
          print("Thank you for playing")
      else :
        print("Incorrect answer")
        print("Thank you for playing")
    else :
      print("Incorrect answer")
      print("Thank you for playing")
  else :
      print("Incorrect answer")
      print("Thank you for playing")
else :
  print("Incorrect answer")
  print("Thank you for playing")
